#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

echo "🚀 Running pre-commit checks..."

npx lint-staged

echo "🔍 TypeScript type checking..."
npm run prebuild

echo "🧪 Running tests..."
npm run test
